In [ ]:
student1 = [69, 78, 72 ,91, 85]
student2 = [75, 92, 92 ,76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print('===========')

In [ ]:
student1 + student2

python 有三個擴充的套件
numpy
Series
DataFrame

In [3]:
import numpy as np
from numpy import ndarray

student1:ndarray = np.array([69, 78, 72 ,91, 85])
student2:ndarray = np.array([75, 92, 92 ,76, 92])

sums:ndarray = student1 + student2
multiplex = student1 * student2
print(sums)
print(multiplex)

for sum in sums:
    print(sum)

[144 170 164 167 177]
[5175 7176 6624 6916 7820]
144
170
164
167
177


In [4]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim , shape,size,dtype
print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)



[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [5]:
np.random.randint(50,101,size=(50,5))

array([[ 82,  93,  53,  90,  95],
       [ 77,  70,  76,  60,  93],
       [ 52,  59,  94,  66,  57],
       [ 80,  59,  50,  97,  59],
       [ 92,  81,  94,  65,  93],
       [ 78,  79,  50,  79,  98],
       [ 76,  98,  67,  53,  74],
       [ 73,  75,  85,  65,  94],
       [ 63, 100,  92,  87,  61],
       [ 61,  87,  52,  82,  53],
       [ 71,  79,  92,  75,  63],
       [ 73,  91,  85,  98,  91],
       [ 92,  94,  99,  90,  77],
       [100,  74,  66,  58,  68],
       [ 77,  61,  96,  91,  69],
       [ 70,  73,  62,  82,  97],
       [ 50,  80,  99,  52,  68],
       [ 62,  82,  51,  98,  90],
       [ 91,  80,  94,  68,  54],
       [ 54,  92,  95,  90,  62],
       [ 62,  50,  86,  87,  61],
       [ 80,  60,  69,  64,  53],
       [ 79,  50,  96,  77,  95],
       [ 71,  83,  77,  67,  61],
       [ 76,  82,  68,  95,  61],
       [ 80,  69,  90,  96,  98],
       [ 59,  90,  57,  71,  60],
       [ 73,  60,  68,  50,  62],
       [ 95,  61,  74,  60,  99],
       [ 62,  